# Generated by Django 5.0.4 on 2024-04-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now=True)),
                ('modificado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
