# Generated by Django 5.0.4 on 2024-04-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
