# Generated by Django 5.0.4 on 2024-04-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_alter_autor_creado_alter_autor_modificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
